create table users (
  id bigint generated by default as identity primary key,
  email varchar(255) not null unique,
  password_hash varchar(255) not null,
  display_name varchar(255) not null,
  role varchar(50) not null,
  enabled boolean not null default true,
  created_at timestamp not null default current_timestamp
);

create table tickets (
  id bigint generated by default as identity primary key,
  title varchar(200) not null,
  description varchar(4000) not null,
  priority varchar(20) not null,
  status varchar(30) not null,
  created_by_id bigint not null,
  assigned_to_id bigint null,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  resolved_at timestamp null,
  closed_at timestamp null,
  constraint fk_ticket_created_by foreign key (created_by_id) references users(id),
  constraint fk_ticket_assigned_to foreign key (assigned_to_id) references users(id)
);

create table ticket_comments (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null,
  author_id bigint not null,
  body varchar(4000) not null,
  internal_note boolean not null default false,
  created_at timestamp not null default current_timestamp,
  constraint fk_comment_ticket foreign key (ticket_id) references tickets(id),
  constraint fk_comment_author foreign key (author_id) references users(id)
);

create table audit_events (
  id bigint generated by default as identity primary key,
  actor_id bigint null,
  entity_type varchar(50) not null,
  entity_id bigint not null,
  action varchar(50) not null,
  created_at timestamp not null default current_timestamp
);